name: Deploy Model to Cloud

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Generate models
        run: bash ./contrib/prepare_dir.sh
      - name: Build Docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build \
            --cache-from ghcr.io/${{ github.repository }}:build-cache \
            --cache-to ghcr.io/${{ github.repository }}:build-cache \
            --push -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
      - name: Deploy to Cloud
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Deploying to Cloud..."
          # Thanks to https://github.com/marketplace/actions/deploy-to-render-current-commit-only
          curl -X POST "https://api.render.com/deploy/deploy/${{ secrets.CLOUD_TOKEN }}&imgURL=ghcr.io/${{ github.repository }}:${{ github.sha }}"
